### ISSUE TITLE
checkgoogleip作者已经潜水了，只能来这求助了

### ISSUE THREAD

**Issue by lsnmx** [xyuanmu/checkiptools#1]
@xyuanmu 停止扫描后，重新打开就这样，麻烦了，checkgoogleip作者已经潜水了，只能来这求助了，用checkiptools横扫亚洲地区除CN外所有IP啊，横扫了3天3夜一退去再重新开始就不行了 也是这问题
D:\Program Files (x86)\Goagent X\CheckIptools>"D:\Program Files (x86)\Goagent X\CheckIptools\python27.exe" "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py"
[MainThread]load last result,ok cnt:51780,ok file line:0,error cnt: 22517116
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 1064, in <module>
    list_ping()
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 994, in list_ping
    ramdomip_thread = RamdomIP(checkqueue,cacheResult,lastokresult|lasterrorresult)

**Comment by xyuanmu** [comment]
@lsnmx 已经可以自动分割，将 googleip-数字.txt 里的IP复制到 googleip.txt 里扫描即可
