### ISSUE TITLE
如何解决ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by lsnmx** [xyuanmu/checkiptools#12]
谢谢 @xyuanmu 
Traceback (most recent call last):
File "python27.py", line 95, in 
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 1101, in 
main()
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 1084, in main
list_ping(g_googleipfile)
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 989, in list_ping
lastokresult,lasterrorresult = cacheResult.loadLastResult()
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 405, in loadLastResult
errorresult.add(from_string(item))
File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 843, in from_string
return reduce(lambda a, b: a << 8 | b, map(int, s.split(".")))
ValueError: invalid literal for int() with base 10: ''

**Comment by xyuanmu** [comment]
你是不是删了什么代码？

**Comment by lsnmx** [comment]
@xyuanmu 没修改什么啊，卡在这好几天了
